"""Add cascade delete scores

Revision ID: 9038545e546b
Revises: d21e87cbf76d
Create Date: 2024-05-31 16:05:19.331740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9038545e546b'
down_revision: Union[str, None] = 'd21e87cbf76d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('scores_student_id_fkey', 'scores', type_='foreignkey')
    op.create_foreign_key(None, 'scores', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.create_foreign_key('scores_student_id_fkey', 'scores', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###
